### PR TITLE
FIX: synchronous events unsubscribed error

### LINKED ISSUE #33: AutoUnsubsribe changes angular semantics of ngOnDestroy
Angular allows a component to issue synchronous events within its `ngOnDestroy` lifecycle hook (see https://github.com/angular/angular/blame/28bdeeef3e954fd13b029f9bc9b1109d22385a1b/packages/core/test/linker/change_detection_integration_spec.ts#L1121 for a test describing the behavior)

AutoUnsubscribe changes that behavior because it _first_ calls unsubscribe on everyting that has an `unsubscribe` function and _then_ calls the `ngOnDestroy` hook. If you try to emit anything within the `ngOnDestroy` hook you will get an exception because each `EventEmitter` has an `unsubscribe` function.

It should be thought about changing the call order of the original `ngOnDestory` hook and the unsubscribe logic.

### PR DESCRIPTION
**Pull request by AdrienRedon**
Fixes #33

### CODE REVIEW

File: src/auto-unsubscribe.ts [hunk 1]
```diff
@@ -28,6 +28,8 @@ export function AutoUnsubscribe({
     }
 
     constructor.prototype[event] = function() {
+      isFunction(original) && original.apply(this, arguments);
+
       if (arrayName) {
         doUnsubscribeIfArray(this[arrayName]);
         isFunction(original) && original.apply(this, arguments);
```
Comment (NetanelBasal) [inline src/auto-unsubscribe.ts]: What about this one?

Comment (AdrienRedon) [reply src/auto-unsubscribe.ts]: oops missed that
